import java.util.ArrayList;

public class Populator {
	public static ArrayList<Episode> run() {
		
		ArrayList<Episode> episodes = new ArrayList<Episode>();
		
	/*	episodes.add(new Episode("1", "1", "Simpsons Roasting on an Open Fire", "December 17, 1989"));
		episodes.add(new Episode("1", "2", "Bart the Genius", "January 14, 1990"));
		episodes.add(new Episode("1", "3", "Homer's Odyssey", "November 1, 1990"));
		episodes.add(new Episode("1", "4", "There's No Disgrace Like Home", "January 28, 1990"));
		episodes.add(new Episode("1", "5", "Bart the General", "February 4, 1990"));
		episodes.add(new Episode("1", "6", "Moaning Lisa", "February 11, 1990"));
	    episodes.add(new Episode("1", "7", "The Call of the Simpsons", "February 18, 1990"));
	    episodes.add(new Episode("1", "8", "The Telltale Head", "February 25, 1990"));
	    episodes.add(new Episode("1", "9", "Life on the Fast Lane", "March 18, 1990"));
	    episodes.add(new Episode("1", "10", "Homer's Night Out", "March 25, 1990"));
	    episodes.add(new Episode("1", "11", "The Crepes of Wrath", "April 15, 1990"));
	    episodes.add(new Episode("1", "12", "Krusty Gets Busted", "April 29, 1990"));
	    episodes.add(new Episode("1", "13", "Some Enchanted Evening", "May 13, 1990")); */
		
		episodes.add(new Episode("2", "1", "Bart Gets an \"F\"", "October 11, 1990"));
        episodes.add(new Episode("2", "2", "Simpson and Delilah", "October 18, 1990"));
        episodes.add(new Episode("2", "3", "Treehouse of Horror", "October 25, 1990"));
        episodes.add(new Episode("2", "4", "Two Cars in Every Garage and Three Eyes on Every Fish", "November 1, 1990"));
        episodes.add(new Episode("2", "5", "Dancin' Homer", "November 8, 1990"));
        episodes.add(new Episode("2", "6", "Dead Putting Society", "November 15, 1990"));
        episodes.add(new Episode("2", "7", "Bart vs. Thanksgiving", "November 22, 1990"));
        episodes.add(new Episode("2", "8", "Bart the Daredevil", "December 6, 1990"));
        episodes.add(new Episode("2", "9", "Itchy & Scratchy & Marge", "December 20, 1990"));
        episodes.add(new Episode("2", "10", "Bart Gets Hit by a Car", "January 10, 1991"));
        episodes.add(new Episode("2", "11", "One Fish, Two Fish, Blowfish, Blue Fish", "January 24, 1991"));
        episodes.add(new Episode("2", "12", "The Way We Was", "January 31, 1991"));
        episodes.add(new Episode("2", "13", "Homer vs. Lisa and the 8th Commandment", "February 7, 1991"));
        episodes.add(new Episode("2", "14", "Principal Charming", "February 14, 1991"));
        episodes.add(new Episode("2", "15", "Oh Brother, Where Art Thou?", "February 21, 1991"));
        episodes.add(new Episode("2", "16", "Bart's Dog Gets an \"F\"", "March 7, 1991"));
        episodes.add(new Episode("2", "17", "Old Money", "March 28, 1991"));
        episodes.add(new Episode("2", "18", "Brush with Greatness", "April 11, 1991"));
        episodes.add(new Episode("2", "19", "Lisa's Substitute", "April 25, 1991"));
        episodes.add(new Episode("2", "20", "The War of the Simpsons", "May 2, 1991"));
        episodes.add(new Episode("2", "21", "Three Men and a Comic Book", "May 9, 1991"));
        episodes.add(new Episode("2", "22", "Blood Feud", "July 11, 1991"));
    
        episodes.add(new Episode("3", "1", "Stark Raving Dad", "September 19, 1991"));
        episodes.add(new Episode("3", "2", "Mr. Lisa Goes to Washington", "September 26, 1991"));
        episodes.add(new Episode("3", "3", "When Flanders Failed", "October 3, 1991"));
        episodes.add(new Episode("3", "4", "Bart the Murderer", "October 10, 1991"));
        episodes.add(new Episode("3", "5", "Homer Defined", "October 17, 1991"));
        episodes.add(new Episode("3", "6", "Like Father, Like Clown", "October 24, 1991"));
        episodes.add(new Episode("3", "7", "Treehouse of Horror II", "October 31, 1991"));
        episodes.add(new Episode("3", "8", "Lisa's Pony", "November 7, 1991"));
        episodes.add(new Episode("3", "9", "Saturdays of Thunder", "November 14, 1991"));
        episodes.add(new Episode("3", "10", "Falming Moe's", "November 21, 1991"));
        episodes.add(new Episode("3", "11", "Burns Verkaufen der Kraftwerk", "December 5, 1991"));
        episodes.add(new Episode("3", "12", "I Married Marge", "December 26, 1991"));
        episodes.add(new Episode("3", "13", "Radio Bart", "January 9, 1992"));
        episodes.add(new Episode("3", "14", "Lisa the Greek", "January 23, 1992"));
        episodes.add(new Episode("3", "15", "Homer Alone", "February 6, 1992"));
        episodes.add(new Episode("3", "16", "Bart the Lover", "February 13, 1992"));
        episodes.add(new Episode("3", "17", "Homer at the Bat", "February 20, 1992"));
        episodes.add(new Episode("3", "18", "Separate Vocations", "February 27, 1992"));
        episodes.add(new Episode("3", "19", "Dog of Death", "March 12, 1992"));
        episodes.add(new Episode("3", "20", "Colonel Homer", "March 26, 1992"));
        episodes.add(new Episode("3", "21", "Black Widower", "April 9, 1992"));
        episodes.add(new Episode("3", "22", "The Otto Show", "April 23, 1992"));
        episodes.add(new Episode("3", "23", "Bart's Friend Falls in Love", "May 7, 1992"));
        episodes.add(new Episode("3", "24", "Brother, Can You Spare Two Dimes?", "August 27, 1992"));
    
    /*    episodes.add(new Episode("4", "1", "Kamp Krusty", "September 24, 1992"));
        episodes.add(new Episode("4", "2", "A Streetcar Named", "October 1, 1992"));
        episodes.add(new Episode("4", "3", "Homer the Heretic", "October 8, 1992"));
        episodes.add(new Episode("4", "4", "Lisa the Beauty Queen", "October 15, 1992"));
        episodes.add(new Episode("4", "5", "Treehouse of Horror III", "October 29, 1992"));
        episodes.add(new Episode("4", "6", "Itchy & Scratchy: The Movie", "November 3, 1992"));
        episodes.add(new Episode("4", "7", "Marge Gets a Job", "November 5, 1992"));
        episodes.add(new Episode("4", "8", "New Kid on the Block", "November 12, 1992"));
        episodes.add(new Episode("4", "9", "Mr. Plow", "November 19, 1992"));
        episodes.add(new Episode("4", "10", "Lisa's First Word", "December 3, 1992"));
        episodes.add(new Episode("4", "11", "Homer's Triple Bypass", "December 17, 1992"));
        episodes.add(new Episode("4", "12", "Marge vs. the Monorail", "January 14, 1993"));
        episodes.add(new Episode("4", "13", "Selma's Choice", "January 21, 1993"));
        episodes.add(new Episode("4", "14", "Brother from the Same Planet", "February 4, 1993"));
        episodes.add(new Episode("4", "15", "I Love Lisa", "February 11, 1993"));
        episodes.add(new Episode("4", "16", "Duffless", "February 18, 1993"));
        episodes.add(new Episode("4", "17", "Last Exit to Springfield", "March 11, 1993"));
        episodes.add(new Episode("4", "18", "So It's Come to This: A Simpsons Clip Show", "April 1, 1993"));
        episodes.add(new Episode("4", "19", "The Front", "April 15, 1993"));
        episodes.add(new Episode("4", "20", "Whacking Day", "April 29, 1993"));
        episodes.add(new Episode("4", "21", "Marge in Chains", "May 6, 1993"));
        episodes.add(new Episode("4", "22", "Krusty Gets Kancelled", "May 13, 1993"));*/
    
        episodes.add(new Episode("5", "1", "Homer's Barbershop Quartet", "September 30, 1993"));
        episodes.add(new Episode("5", "2", "Cape Feare", "October 7, 1993"));
        episodes.add(new Episode("5", "3", "Homer Goes to College", "October 14, 1993"));
        episodes.add(new Episode("5", "4", "Rosebud", "October 21, 1993"));
        episodes.add(new Episode("5", "5", "Treehouse of Horror IV", "October 28, 1993"));
        episodes.add(new Episode("5", "6", "Marge on the Lam", "November 4, 1993"));
        episodes.add(new Episode("5", "7", "Bart's Inner Child", "November 11, 1993"));
        episodes.add(new Episode("5", "8", "Boy-Scoutz 'n the Hood", "November 18, 1993"));
        episodes.add(new Episode("5", "9", "The Last Temptation of Homer", "December 9, 1993"));
        episodes.add(new Episode("5", "10", "$pringfield (or, How I Learned to Stop Worrying and Love Legalized Gambling)", "December       16, 1993"));
        episodes.add(new Episode("5", "11", "Homer the Vigilante", "January 6, 1994"));
        episodes.add(new Episode("5", "12", "Bart Gets Famous", "February 3, 1994"));
        episodes.add(new Episode("5", "13", "Homer and Apu", "February 10, 1994"));
        episodes.add(new Episode("5", "14", "Lisa vs. Malibu Stacy", "February 17, 1994"));
        episodes.add(new Episode("5", "15", "Deep Space Homer", "February 24, 1994"));
        episodes.add(new Episode("5", "16", "Homer Loves Flanders", "March 17, 1994"));
        episodes.add(new Episode("5", "17", "Bart Gets an Elephant", "March 31, 1994"));
        episodes.add(new Episode("5", "18", "Burns Heir", "April 14, 1994"));
        episodes.add(new Episode("5", "19", "Sweet Seymour Skinner's Baadasssss Song", "April 28, 1994"));
        episodes.add(new Episode("5", "20", "The Boy Who Knew Too Much", "May 5, 1994"));
        episodes.add(new Episode("5", "21", "Lady Bouvier's Lover", "May 12, 1994"));
        episodes.add(new Episode("5", "22", "Secrets of a Successful Marriage", "May 19, 1994"));
    
        episodes.add(new Episode("6", "1", "Bart of Darkness", "September 4, 1994"));
        episodes.add(new Episode("6", "2", "Lisa's Rival", "September 11, 1994"));
        episodes.add(new Episode("6", "3", "Another Simpsons Clip Show", "September 25, 1994"));
        episodes.add(new Episode("6", "4", "Itchy & Scratchy Land", "October 2, 1992"));
        episodes.add(new Episode("6", "5", "Sideshow Bob Roberts", "October 9, 1994"));
        episodes.add(new Episode("6", "6", "Treehouse of Horror V", "October 30, 1994"));
        episodes.add(new Episode("6", "7", "Bart's Girlfriend", "November 6, 1994"));
        episodes.add(new Episode("6", "8", "Lisa on Ice", "November 13, 1994"));
        episodes.add(new Episode("6", "9", "Homer Badman", "November 27, 1994"));
        episodes.add(new Episode("6", "10", "Grampa vs. Sexual Inadequacy", "December 4, 1994"));
        episodes.add(new Episode("6", "11", "Fear of Flying", "December 18, 1994"));
        episodes.add(new Episode("6", "12", "Homer the Great", "January 8, 1995"));
        episodes.add(new Episode("6", "13", "And Maggie Makes Three", "January 22, 1995"));
        episodes.add(new Episode("6", "14", "Bart's Comet", "February 5, 1995"));
        episodes.add(new Episode("6", "15", "Homie the Clown", "February 12, 1995"));
        episodes.add(new Episode("6", "16", "Bart vs. Australia", "February 19, 1995"));
        episodes.add(new Episode("6", "17", "Homer vs. Patty and Selma", "February 26, 1995"));
        episodes.add(new Episode("6", "18", "A Star Is Burns", "March 5, 1995"));
        episodes.add(new Episode("6", "19", "Lisa's Wedding", "March 19, 1995"));
        episodes.add(new Episode("6", "20", "Two Dozen and One Greyhounds", "April 9, 1995"));
        episodes.add(new Episode("6", "21", "The PTA Disbands", "April 16, 1995"));
        episodes.add(new Episode("6", "22", "Round Springfield", "April 30, 1995"));
        episodes.add(new Episode("6", "23", "The Springfield Connection", "May 7, 1995"));
        episodes.add(new Episode("6", "24", "Lemon of Troy", "May 14, 1995"));
        episodes.add(new Episode("6", "25", "Who Shot Mr. Burns? (Part One)", "May 21, 1995"));
    
        episodes.add(new Episode("7", "1", "Who Shot Mr. Burns? (Part Two)", "September 17, 1995"));
        episodes.add(new Episode("7", "2", "Radioactive Man", "September 24, 1995"));
        episodes.add(new Episode("7", "3", "Home Sweet Homediddly-Dum-Doodily", "October 1, 1995"));
        episodes.add(new Episode("7", "4", "Bart Sells His Soul", "October 8, 1995"));
        episodes.add(new Episode("7", "5", "Lisa the Vegetarian", "October 15, 1995"));
        episodes.add(new Episode("7", "6", "Treehouse of Horror VI", "October 29, 1995"));
        episodes.add(new Episode("7", "7", "King-Size Homer", "November 5, 1995"));
        episodes.add(new Episode("7", "8", "Mother Simpson", "November 19, 1995"));
        episodes.add(new Episode("7", "9", "Sideshow Bob's Last Gleaming", "November 26, 1995"));
        episodes.add(new Episode("7", "10", "The Simpsons 138th Episode Spectacular", "December 3, 1995"));
        episodes.add(new Episode("7", "11", "Marge Be Not Proud", "December 17, 1995"));
        episodes.add(new Episode("7", "12", "Team Homer", "January 7, 1996"));
        episodes.add(new Episode("7", "13", "Two Bad Neighbors", "January 14, 1996"));
        episodes.add(new Episode("7", "14", "Scenes from the Class Struggle in Springfield", "February 4, 1996"));
        episodes.add(new Episode("7", "15", "Bart the Fink", "February 11, 1996"));
        episodes.add(new Episode("7", "16", "Lisa the Iconoclast", "February 18, 1996"));
        episodes.add(new Episode("7", "17", "Homer the Smithers", "February 25, 1996"));
        episodes.add(new Episode("7", "18", "The Day the Violence Died", "March 17, 1996"));
        episodes.add(new Episode("7", "19", "A Fish Called Selma", "March 24, 1996"));
        episodes.add(new Episode("7", "20", "Bart on the Road", "March 31, 1996"));
        episodes.add(new Episode("7", "21", "22 Short Films About Springfield", "April 14, 1996"));
        episodes.add(new Episode("7", "22", "Raging Abe Simpson and His Grumbling Grandson in \"The Curse of the Flying Hellfish\"",        "April 28, 1996"));
        episodes.add(new Episode("7", "23", "Much Apu About Nothing", "May 5, 1996"));
        episodes.add(new Episode("7", "24", "Homerpalooza", "May 19, 1996"));
        episodes.add(new Episode("7", "25", "Summer of 4 Ft. 2", "May 19, 1996"));
    
        episodes.add(new Episode("8", "1", "Treehouse of Horror VII", "October 27, 1996"));
        episodes.add(new Episode("8", "2", "You Only Move Twice", "November 3, 1996"));
        episodes.add(new Episode("8", "3", "The Homer They Fall", "November 10, 1996"));
        episodes.add(new Episode("8", "4", "Burns, Baby Burns", "November 17, 1996"));
        episodes.add(new Episode("8", "5", "Bart After Dark", "November 24, 1996"));
        episodes.add(new Episode("8", "6", "A Milhouse Divided", "December 1, 1996"));
        episodes.add(new Episode("8", "7", "Lisa's Date with Density", "December 15, 1996"));
        episodes.add(new Episode("8", "8", "Hurricane Neddy", "December 29, 1996"));
        episodes.add(new Episode("8", "9", "El Viaje Misterioso de Nuestro Jomer (The Mysterious Voyago of Homer)", "January 5,             1997"));
        episodes.add(new Episode("8", "10", "The Springfield Files", "January 12, 1997"));
        episodes.add(new Episode("8", "11", "The Twisted World of Marge Simpson", "January 19, 1997"));
        episodes.add(new Episode("8", "12", "Mountain of Madness", "February 2, 1997"));
        episodes.add(new Episode("8", "13", "Simpsoncalifragilisticexpiala(Annoyed Grunt)cious", "February 7, 1997"));
        episodes.add(new Episode("8", "14", "The Itchy & Scratchy & Poochie Show", "February 9, 1997"));
        episodes.add(new Episode("8", "15", "Homer's Phobia", "February 16, 1997"));
        episodes.add(new Episode("8", "16", "Brother from Another Series", "February 23, 1997"));
        episodes.add(new Episode("8", "17", "My Sister, My Sitter", "March 2, 1997"));
        episodes.add(new Episode("8", "18", "Homer vs. the Eighteenth Amendment", "March 16, 1997"));
        episodes.add(new Episode("8", "19", "Grade School Confidential", "April 6, 1997"));
        episodes.add(new Episode("8", "20", "The Canine Mutiny", "April 13, 1997"));
        episodes.add(new Episode("8", "21", "The Old Man and the Lisa", "April 20, 1997"));
        episodes.add(new Episode("8", "22", "In Marge We Trust", "April 27, 1997"));
        episodes.add(new Episode("8", "23", "Homer's Enemy", "May 4, 1997"));
        episodes.add(new Episode("8", "24", "The Simpsons Spin-Off Showcase", "May 11, 1997"));
        episodes.add(new Episode("8", "25", "The Secret War of Lisa Simpson", "May 18, 1997"));
        
     /*   episodes.add(new Episode("9", "1", "The City of New York vs. Homer Simpson", "September 21, 1997"));
        episodes.add(new Episode("9", "2", "The Principal and the Pauper", "September 28, 1997"));
        episodes.add(new Episode("9", "3", "Lisa's Sax", "October 19, 1997"));
        episodes.add(new Episode("9", "4", "Treehouse of Horror VIII", "October 26, 1997"));
        episodes.add(new Episode("9", "5", "The Cartridge Family", "November 2, 1997"));
        episodes.add(new Episode("9", "6", "Bart Star", "November 9, 1997"));
        episodes.add(new Episode("9", "7", "The Two Mrs. Nahasapeemapetilons", "November 16, 1997"));
        episodes.add(new Episode("9", "8", "Lisa the Skeptic", "November 23, 1997"));
        episodes.add(new Episode("9", "9", "Realty Bites", "December 7, 1997"));
        episodes.add(new Episode("9", "10", "Miracle on Evergreen Terrace", "December 21, 1997"));
        episodes.add(new Episode("9", "11", "All Singing, All Dancing", "January 4, 1998"));
        episodes.add(new Episode("9", "12", "Bart Carny", "January 11, 1998"));
        episodes.add(new Episode("9", "13", "The Joy of Sect", "February 8, 1998"));
        episodes.add(new Episode("9", "14", "Das Bus", "February 15, 1998"));
        episodes.add(new Episode("9", "15", "The Last Temptation of Krust", "February 22, 1998"));
        episodes.add(new Episode("9", "16", "Dumbbell Idemnity", "March 1, 1998"));
        episodes.add(new Episode("9", "17", "Lisa the Simpson", "March 8, 1998"));
        episodes.add(new Episode("9", "18", "This Little Wiggy", "March 22, 1998"));
        episodes.add(new Episode("9", "19", "Simpson Tide", "March 29, 1998"));
        episodes.add(new Episode("9", "20", "The Trouble with Trillions", "April 5, 1998"));
        episodes.add(new Episode("9", "21", "Girly Edition", "April 19, 1998"));
        episodes.add(new Episode("9", "22", "Trash of the Titans", "April 26, 1998"));
        episodes.add(new Episode("9", "23", "King of the Hill", "May 3, 1998"));
        episodes.add(new Episode("9", "24", "Lost Our Lisa", "May 10, 1998"));
        episodes.add(new Episode("9", "25", "Natural Born Kissers", "May 17, 1998"));*/
    
        episodes.add(new Episode("10", "1", "Lard of the Dance", "August 23, 1998"));
        episodes.add(new Episode("10", "2", "The Wizard of Evergreen Terrace", "September 20, 1998"));
        episodes.add(new Episode("10", "3", "Bart the Mother", "September 27, 1998"));
        episodes.add(new Episode("10", "4", "Treehouse of Horror IX", "October 25, 1998"));
        episodes.add(new Episode("10", "5", "When You Dish Upon a Star", "November 8, 1998"));
        episodes.add(new Episode("10", "6", "D'oh-in' in the Wind", "November 15, 1998"));
        episodes.add(new Episode("10", "7", "Lisa Gets and \"A\"", "November 22, 1998"));
        episodes.add(new Episode("10", "8", "Homer Simpson in: \"Kidney Trouble\"", "December 6, 1998"));
        episodes.add(new Episode("10", "9", "Mayored to the Mob", "December 20, 1998"));
        episodes.add(new Episode("10", "10", "Viva Ned Flanders", "January 10, 1999"));
        episodes.add(new Episode("10", "11", "Wild Barts Can't Be Broken", "January 17, 1999"));
        episodes.add(new Episode("10", "12", "Sunday, Cruddy Sunday", "January 31, 1999"));
        episodes.add(new Episode("10", "13", "Homer to the Max", "February 7, 1999"));
        episodes.add(new Episode("10", "14", "I'm with Cupid", "February 14, 1999"));
        episodes.add(new Episode("10", "15", "Marge Simpson in: \"Screaming Yellow Honkers\"", "February 21, 1999"));
        episodes.add(new Episode("10", "16", "Make Room for Lisa", "February 28, 1999"));
        episodes.add(new Episode("10", "17", "Maximum Homerdrive", "March 28, 1999"));
        episodes.add(new Episode("10", "18", "Simpsons Bible Stories", "April 4, 1999"));
        episodes.add(new Episode("10", "19", "Mom and Pop Art", "April 11, 1999"));
        episodes.add(new Episode("10", "20", "The Old Man and the \"C\" Student", "April 25, 1999"));
        episodes.add(new Episode("10", "21", "Monty Can't Buy Me Love", "May 2, 1999"));
        episodes.add(new Episode("10", "22", "They Saved Lisa's Brain", "May 9, 1999"));
        episodes.add(new Episode("10", "23", "Thirty Minutes over Tokyo", "May 16, 1999"));
    
        episodes.add(new Episode("11", "1", "Beyond Blunderdome", "September 26, 1999"));
        episodes.add(new Episode("11", "2", "Brother's Little Helper", "October 3, 1999"));
        episodes.add(new Episode("11", "3", "Guess Who's Coming to Criticize Dinner?", "October 24, 1999"));
        episodes.add(new Episode("11", "4", "Treehouse of Horror X", "October 31, 1999"));
        episodes.add(new Episode("11", "5", "E-I-E-I-(Annoyed Grunt)", "November 7, 1999"));
        episodes.add(new Episode("11", "6", "Hello Gutter, Hello Fadder", "November 14, 1999"));
        episodes.add(new Episode("11", "7", "Eight Misbehavin", "November 21, 1999"));
        episodes.add(new Episode("11", "8", "Take My Wife, Sleaze", "November 28, 1999"));
        episodes.add(new Episode("11", "9", "Grift of the Magi", "December 19, 1999"));
        episodes.add(new Episode("11", "10", "Little Big Mom", "January 9, 2000"));
        episodes.add(new Episode("11", "11", "Faith Off", "January 16, 2000"));
        episodes.add(new Episode("11", "12", "The Mansion Family", "January 23, 2000"));
        episodes.add(new Episode("11", "13", "Saddlesore Galatica", "February 6, 2000"));
        episodes.add(new Episode("11", "14", "Alone Again, Natura-Diddly", "February 13, 2000"));
        episodes.add(new Episode("11", "15", "Missionary; Impossible", "February 20, 2000"));
        episodes.add(new Episode("11", "16", "Pygmoelian", "February 27, 2000"));
        episodes.add(new Episode("11", "17", "Bart to the Future", "March 19, 2000"));
        episodes.add(new Episode("11", "18", "Days of Wine and D'oh'ses", "April 9, 2000"));
        episodes.add(new Episode("11", "19", "Kill the Alligator and Run", "April 30, 2000"));
        episodes.add(new Episode("11", "20", "Last Tap Dance in Springfield", "May 7, 2000"));
        episodes.add(new Episode("11", "21", "It's a Mad, Mad, Mad, Mad Marge", "May 14, 2000"));
        episodes.add(new Episode("11", "22", "Behind the Laughter", "May 21, 2000"));
    
        episodes.add(new Episode("12", "1", "Treehouse of Horror XI", "November 1, 2000"));
        episodes.add(new Episode("12", "2", "A Tale of Two Springfields", "November 5, 2000"));
        episodes.add(new Episode("12", "3", "Insane Clown Poppy", "November 12, 2000"));
        episodes.add(new Episode("12", "4", "Lisa the Tree Hugger", "November 19, 2000"));
        episodes.add(new Episode("12", "5", "Homer vs. Dignity", "November 26, 2000"));
        episodes.add(new Episode("12", "6", "The Computer Wore Menace Shoes", "December 3, 2000"));
        episodes.add(new Episode("12", "7", "The Great Money Caper", "December 10, 2000"));
        episodes.add(new Episode("12", "8", "Skinner's Sense of Snow", "December 17, 2000"));
        episodes.add(new Episode("12", "9", "HOMR", "January 7, 2001"));
        episodes.add(new Episode("12", "10", "Pokey Mom", "January 14, 2001"));
        episodes.add(new Episode("12", "11", "Worst Episode Ever", "February 4, 2001"));
        episodes.add(new Episode("12", "12", "Tennis the Menace", "February 11, 2001"));
        episodes.add(new Episode("12", "13", "Day of the Jackanapes", "February 18, 2001"));
        episodes.add(new Episode("12", "14", "New Kids on the Blecch", "February 25, 2001"));
        episodes.add(new Episode("12", "15", "Hungry, Hungry Homer", "March 4, 2001"));
        episodes.add(new Episode("12", "16", "Bye Bye Nerdie", "March 11, 2001"));
        episodes.add(new Episode("12", "17", "Simpson Safari", "April 1, 2001"));
        episodes.add(new Episode("12", "18", "Trilogy of Error", "April 29, 2001"));
        episodes.add(new Episode("12", "19", "I'm Goin' to Praiseland", "May 6, 2001"));
        episodes.add(new Episode("12", "20", "Children of a Lesser Clod", "May 13, 2001"));
        episodes.add(new Episode("12", "21", "Simpsons Tall Tales", "May 20, 2001"));
        
        episodes.add(new Episode("13", "1", "Treehouse of Horror XII", "November 6, 2001"));
        episodes.add(new Episode("13", "2", "The Parent Rap", "November 11, 2001"));
        episodes.add(new Episode("13", "3", "Homer the Moe", "November 18, 2001"));
        episodes.add(new Episode("13", "4", "A Hunka Hunka Burns in Love", "December 2, 2001"));
        episodes.add(new Episode("13", "5", "The Blunder Years", "December 9, 2001"));
        episodes.add(new Episode("13", "6", "She of Little Faith", "December 16, 2001"));
        episodes.add(new Episode("13", "7", "Brawl in the Family", "January 6, 2002"));
        episodes.add(new Episode("13", "8", "Sweets and Sour Marge", "January 20, 2002"));
        episodes.add(new Episode("13", "9", "Jaws Wired Shut", "January 27, 2002"));
        episodes.add(new Episode("13", "10", "Half-Decent Proposal", "February 10, 2002"));
        episodes.add(new Episode("13", "11", "The Bart Wants What It Wants", "February 17, 2002"));
        episodes.add(new Episode("13", "12", "The Lastest Gun in the West", "February 24, 2002"));
        episodes.add(new Episode("13", "13", "The Old Man and the Key", "March 10, 2002"));
        episodes.add(new Episode("13", "14", "Tales from the Public Domain", "March 17, 2002"));
        episodes.add(new Episode("13", "15", "Blame It on Lisa", "March 31, 2002"));
        episodes.add(new Episode("13", "16", "Weekend at Burnsie's", "April 7, 2002"));
        episodes.add(new Episode("13", "17", "Gump Roast", "April 21, 2002"));
        episodes.add(new Episode("13", "18", "I Am Furious (Yellow)", "April 28, 2002"));
        episodes.add(new Episode("13", "19", "The Sweetest Apu", "May 5, 2002"));
        episodes.add(new Episode("13", "20", "Little Girl in the Big Ten", "May 12, 2002"));
        episodes.add(new Episode("13", "21", "The Frying Game", "May 19, 2002"));
        episodes.add(new Episode("13", "22", "Poppa's Got a Brand New Badge", "May 22, 2002"));
        
        episodes.add(new Episode("14", "1", "Treehouse of Horror XIII", "November 3, 2002"));
        episodes.add(new Episode("14", "2", "How I Spent My Strummer Vacation", "November 10, 2002"));
        episodes.add(new Episode("14", "3", "Bart vs. Lisa vs. the Third Grade", "November 17, 2002"));
        episodes.add(new Episode("14", "4", "Large Marge", "November 24, 2002"));
        episodes.add(new Episode("14", "5", "Helter Shelter", "December 1, 2002"));
        episodes.add(new Episode("14", "6", "The Great Louse Detective", "December 15, 2002"));
        episodes.add(new Episode("14", "7", "Special Edna", "January 5, 2003"));
        episodes.add(new Episode("14", "8", "The Dad Who Knew Too Little", "January 12, 2003"));
        episodes.add(new Episode("14", "9", "The Strong Arms of the Ma", "February 2, 2003"));
        episodes.add(new Episode("14", "10", "Pray Anything", "February 9, 2003"));
        episodes.add(new Episode("14", "11", "Barting Over", "February 16, 2003"));
        episodes.add(new Episode("14", "12", "I'm Spelling as Fast as I Can", "February 16, 2003"));
        episodes.add(new Episode("14", "13", "A Star Is Born Again", "March 2, 2003"));
        episodes.add(new Episode("14", "14", "Mr. Spritz Goes to Washington", "March 9, 2003"));
        episodes.add(new Episode("14", "15", "C.E.D'oh", "March 16, 2003"));
        episodes.add(new Episode("14", "16", "Scuse Me While I Miss the Sky", "March 30, 2003"));
        episodes.add(new Episode("14", "17", "Three Gays of the Condo", "April 13, 2003"));
        episodes.add(new Episode("14", "18", "Dude, Where's My Ranch?", "April 27, 2003"));
        episodes.add(new Episode("14", "19", "Old Yeller-Belly", "May 4, 2003"));
        episodes.add(new Episode("14", "20", "Brake My Wife, Please", "May 11, 2003"));
        episodes.add(new Episode("14", "21", "The Bart of War", "May 18, 2003"));
        episodes.add(new Episode("14", "22", "Moe Baby Blues", "May 18, 2003"));
        
        episodes.add(new Episode("15", "1", "Treehouse of Horror XIV", "November 2, 2003"));
        episodes.add(new Episode("15", "2", "My Mother the Carjacker", "November 9, 2003"));
        episodes.add(new Episode("15", "3", "The President Wore Pearls", "November 16, 2003"));
        episodes.add(new Episode("15", "4", "The Regina Monologues", "November 23, 2003"));
        episodes.add(new Episode("15", "5", "The Fat and the Furriest", "November 30, 2003"));
        episodes.add(new Episode("15", "6", "Today I Am a Clown", "December 7, 2003"));
        episodes.add(new Episode("15", "7", "Tis the Fifteenth Season", "December 14, 2003"));
        episodes.add(new Episode("15", "8", "Marge vs. Singles, Seniors, Childless Couples and Teens and Gays", "January 4, 2004"));
        episodes.add(new Episode("15", "9", "I, (Annoyed Grunt)-bot", "January 11, 2004"));
        episodes.add(new Episode("15", "10", "Diatribe of a Mad Housewife", "January 25, 2004"));
        episodes.add(new Episode("15", "11", "Margical History Tour", "February 15, 2004"));
        episodes.add(new Episode("15", "12", "Milhouse Doesn't Live Here Anymore", "February 15, 2004"));
        episodes.add(new Episode("15", "13", "Smart & Smarter", "February 22, 2004"));
        episodes.add(new Episode("15", "14", "The Ziff Who Came to Dinner", "March 14, 2004"));
        episodes.add(new Episode("15", "15", "Co-Dependents' Day", "March 21, 2004"));
        episodes.add(new Episode("15", "16", "The Wandering Juvie", "March 28, 2004"));
        episodes.add(new Episode("15", "17", "My Big Fat Greek Wedding", "April 18, 2004"));
        episodes.add(new Episode("15", "18", "Catch 'Em If You Can", "April 25, 2004"));
        episodes.add(new Episode("15", "19", "Simple Simpson", "May 2, 2004"));
        episodes.add(new Episode("15", "20", "The Way We Weren't", "May 9, 2004"));
        episodes.add(new Episode("15", "21", "Bart-Mangled Banner", "May 16, 2004"));
        episodes.add(new Episode("15", "22", "Fraudcast News", "May 23, 2004"));
        
        episodes.add(new Episode("16", "1", "Treehouse of Horror XV", "November 7, 2004"));
        episodes.add(new Episode("16", "2", "All's Fair in Oven War", "November 14, 2004"));
        episodes.add(new Episode("16", "3", "Sleeping with the Enemy", "November 21, 2004"));
        episodes.add(new Episode("16", "4", "She Used to Be My Girl", "December 5, 2004"));
        episodes.add(new Episode("16", "5", "Fat Man and Little Boy", "December 12, 2004"));
        episodes.add(new Episode("16", "6", "Midnight Rx", "January 16, 2005"));
        episodes.add(new Episode("16", "7", "Mommie Beerest", "January 30, 2005"));
        episodes.add(new Episode("16", "8", "Homer and Ned's Hail Mary Pass", "February 6, 2005"));
        episodes.add(new Episode("16", "9", "Pranksta Rap", "February 13, 2005"));
        episodes.add(new Episode("16", "10", "There's Something About Marrying", "February 20, 2005"));
        episodes.add(new Episode("16", "11", "On a Clear Day I Can't See My Sister", "March 6, 2005"));
        episodes.add(new Episode("16", "12", "Goo Goo Gai Pan", "March 13, 2005"));
        episodes.add(new Episode("16", "13", "Mobile Homer", "March 20, 2005"));
        episodes.add(new Episode("16", "14", "The Seven-Beer Snitch", "April 3, 2005"));
        episodes.add(new Episode("16", "15", "Future-Drama", "April 17, 2005"));
        episodes.add(new Episode("16", "16", "Don't Fear the Roofer", "May 1, 2005"));
        episodes.add(new Episode("16", "17", "The Heartbroke Kid", "May 1, 2005"));
        episodes.add(new Episode("16", "18", "A Star is Torn", "May 8, 2005"));
        episodes.add(new Episode("16", "19", "Thank God It's Doomsday", "May 8, 2005"));
        episodes.add(new Episode("16", "20", "Home Away from Homer", "May 15, 2005"));
        episodes.add(new Episode("16", "21", "The Father, the Son, and the Holy Guest Star", "May 15, 2005"));
    
        episodes.add(new Episode("17", "1", "The Bonfire of the Manatees", "September 11, 2005"));
        episodes.add(new Episode("17", "2", "The Girl Who Slept Too Little", "September 18, 2005"));
        episodes.add(new Episode("17", "3", "Milhouse of Sand and Fog", "September 25, 2005"));
        episodes.add(new Episode("17", "4", "Treehouse of Horror XVI", "November 6, 2005"));
        episodes.add(new Episode("17", "5", "Marge's Son Poisoning", "November 13, 2005"));
        episodes.add(new Episode("17", "6", "See Homer Run", "November 20, 2005"));
        episodes.add(new Episode("17", "7", "The Last of the Red Hay Mamas", "November 27, 2005"));
        episodes.add(new Episode("17", "8", "The Italian Bob", "December 11, 2005"));
        episodes.add(new Episode("17", "9", "Simpsons Christmas Stories", "December 18, 2005"));
        episodes.add(new Episode("17", "10", "Homer's Paternity Coot", "January 8, 2006"));
        episodes.add(new Episode("17", "11", "We're on the Road to D'ohwhere", "January 29, 2006"));
        episodes.add(new Episode("17", "12", "My Fair Laddy", "February 26, 2006"));
        episodes.add(new Episode("17", "13", "The Seemingly Never-Ending Story", "March 12, 2006"));
        episodes.add(new Episode("17", "14", "Bart Has Two Mommies", "March 19, 2006"));
        episodes.add(new Episode("17", "15", "Homer Simpson, This Is Your Wife", "March 26, 2006"));
        episodes.add(new Episode("17", "16", "Million-Dollar Abie", "April 2, 2006"));
        episodes.add(new Episode("17", "17", "Kiss Kiss, Bang Bangalore", "April 9, 2006"));
        episodes.add(new Episode("17", "18", "The Wettest Stories Ever Told", "April 23, 2006"));
        episodes.add(new Episode("17", "19", "Girls Just Want to Have Sums", "April 30, 2006"));
        episodes.add(new Episode("17", "20", "Regarding Margie", "May 7, 2006"));
        episodes.add(new Episode("17", "21", "The Monkey Suit", "May 14, 2006"));
        episodes.add(new Episode("17", "22", "Marge and Homer Turn a Couple Play", "May 21, 2006"));
        
        episodes.add(new Episode("18", "1", "The Mook, the Chef, the Wife and Her Homer", "September 10, 2006"));
        episodes.add(new Episode("18", "2", "Jazzy and the Pussycats", "September 17, 2006"));
        episodes.add(new Episode("18", "3", "Please Homer, Don't Hammer 'Em", "September 24, 2006"));
        episodes.add(new Episode("18", "4", "Treehouse of Horror XVII", "November 5, 2006"));
        episodes.add(new Episode("18", "5", "G.I. (Annoyed Grunt)", "November 12, 2006"));
        episodes.add(new Episode("18", "6", "Moe'N'a Lisa", "November 19, 2006"));
        episodes.add(new Episode("18", "7", "Ice Cream of Margie (with the Light Blue Hair)", "November 26, 2006"));
        episodes.add(new Episode("18", "8", "The Haw-Hawed Couple", "December 10, 2006"));
        episodes.add(new Episode("18", "9", "Kill Gil, Volumes I & II", "December 17, 2006"));
        episodes.add(new Episode("18", "10", "The Wife Aquatic", "January 7, 2007"));
        episodes.add(new Episode("18", "11", "Revenge Is a Dish Best Served Three Times", "January 28, 2007"));
        episodes.add(new Episode("18", "12", "Little Big Girl", "February 11, 2007"));
        episodes.add(new Episode("18", "13", "Springfield Up", "February 18, 2007"));
        episodes.add(new Episode("18", "14", "Yokel Chords", "March 4, 2007"));
        episodes.add(new Episode("18", "15", "Rome-Old and Juli-Eh", "March 11, 2007"));
        episodes.add(new Episode("18", "16", "Homerazzi", "March 25, 2007"));
        episodes.add(new Episode("18", "17", "Marge Gamer", "April 22, 2007"));
        episodes.add(new Episode("18", "18", "The Boys of Bummer", "April 29, 2007"));
        episodes.add(new Episode("18", "19", "Crook and Ladder", "May 6, 2007"));
        episodes.add(new Episode("18", "20", "Stop! Or My Dog Will Shoot", "May 13, 2007"));
        episodes.add(new Episode("18", "21", "24 Minutes", "May 20, 2007"));
        episodes.add(new Episode("18", "22", "You Kent Always Say What You Want", "May 20, 2007"));
    
        episodes.add(new Episode("19", "1", "He Loves to Fly and He D'ohs", "September 23, 2007"));
        episodes.add(new Episode("19", "2", "The Homer of Seville", "September 30, 2007"));
        episodes.add(new Episode("19", "3", "Midnight Towboy", "October 7, 2007"));
        episodes.add(new Episode("19", "4", "I Don't Wanna Know Why the Caged Bird Sings", "October 14, 2007"));
        episodes.add(new Episode("19", "5", "Treehouse of Horror XVIII", "November 4, 2007"));
        episodes.add(new Episode("19", "6", "Little Orphan Millie", "November 11, 2007"));
        episodes.add(new Episode("19", "7", "Husbands and Knives", "November 18, 2007"));
        episodes.add(new Episode("19", "8", "Funeral for a Fiend", "November 25, 2007"));
        episodes.add(new Episode("19", "9", "Eternal Moonshine of the Simpson Mind", "December 16, 2007"));
        episodes.add(new Episode("19", "10", "E Pluribus Wiggum", "January 6, 2008"));
        episodes.add(new Episode("19", "11", "That '90s Show", "January 27, 2008"));
        episodes.add(new Episode("19", "12", "Love, Springfieldian Style", "February 17, 2008"));
        episodes.add(new Episode("19", "13", "The Debarted", "March 2, 2008"));
        episodes.add(new Episode("19", "14", "Dial 'N' for Nerder", "March 9, 2008"));
        episodes.add(new Episode("19", "15", "Smoke on the Daughter", "March 30, 2008"));
        episodes.add(new Episode("19", "16", "Papa Don't Leech", "April 13, 2008"));
        episodes.add(new Episode("19", "17", "Apocalypse Cow", "April 27, 2008"));
        episodes.add(new Episode("19", "18", "Any Given Sundance", "May 4, 2008"));
        episodes.add(new Episode("19", "19", "Mona Leaves-a", "May 11, 2008"));
        episodes.add(new Episode("19", "20", "All About Lisa", "May 18, 2008"));
    
        episodes.add(new Episode("20", "1", "Sex, Pies and Idiot Scrapes", "September 28, 2008"));
        episodes.add(new Episode("20", "2", "Lost Verizon", "October 5, 2008"));
        episodes.add(new Episode("20", "3", "Double, Double, Boy in Trouble", "October 19, 2008"));
        episodes.add(new Episode("20", "4", "Treehouse of Horror XIX", "November 2, 2008"));
        episodes.add(new Episode("20", "5", "Dangerous Curves", "November 9, 2008"));
        episodes.add(new Episode("20", "6", "Homer and Lisa Exchange Cross Words", "November 16, 2008"));
        episodes.add(new Episode("20", "7", "MyPods and Boomsticks", "November 30, 2008"));
        episodes.add(new Episode("20", "8", "The Burns and the Bees", "December 7, 2008"));
        episodes.add(new Episode("20", "9", "Lisa the Drama Queen", "January 25, 2009"));
        episodes.add(new Episode("20", "10", "Take My Life, Please", "February 15, 2009"));
        episodes.add(new Episode("20", "11", "How the Test Was Won", "March 1, 2009"));
        episodes.add(new Episode("20", "12", "No Loan Again, Naturally", "March 8, 2009"));
        episodes.add(new Episode("20", "13", "Gone Maggie Gone", "March 15, 2009"));
        episodes.add(new Episode("20", "14", "In the Name of the Grandfather", "March 22, 2009"));
        episodes.add(new Episode("20", "15", "Wedding for Disaster", "March 29, 2009"));
        episodes.add(new Episode("20", "16", "Eeny Teeny Maya Moe", "April 5, 2009"));
        episodes.add(new Episode("20", "17", "The Good, the Sad and the Drugly", "April 19, 2009"));
        episodes.add(new Episode("20", "18", "Father Knows Worst", "April 26, 2009"));
        episodes.add(new Episode("20", "19", "Waverly Hills, 9-0-2-1-D'oh", "May 3, 2009"));
        episodes.add(new Episode("20", "20", "Four Great Women and a Manicure", "May 10, 2009"));
        episodes.add(new Episode("20", "21", "Coming to Homerica", "May 17, 2009"));
    
        episodes.add(new Episode("21", "1", "Homer the Whopper", "September 27, 2009"));
        episodes.add(new Episode("21", "2", "Bart Gets a 'Z'", "October 4, 2009"));
        episodes.add(new Episode("21", "3", "The Great Wife Hope", "October 11, 2009"));
        episodes.add(new Episode("21", "4", "Treehouse of Horror XX", "October 18, 2009"));
        episodes.add(new Episode("21", "5", "The Devil Wears Nada", "November 15, 2009"));
        episodes.add(new Episode("21", "6", "Pranks and Greens", "November 22, 2009"));
        episodes.add(new Episode("21", "7", "Rednecks and Broomsticks", "November 29, 2009"));
        episodes.add(new Episode("21", "8", "O Brother, Where Bart Thou?", "December 13, 2009"));
        episodes.add(new Episode("21", "9", "Thursdays with Abie", "January 3, 2010"));
        episodes.add(new Episode("21", "10", "Once Upon a Time in Springfield", "January 10, 2010"));
        episodes.add(new Episode("21", "11", "Million Dollar Maybe", "January 31, 2010"));
        episodes.add(new Episode("21", "12", "Boy Meets Curl", "February 14, 2010"));
        episodes.add(new Episode("21", "13", "The Color Yellow", "February 21, 2010"));
        episodes.add(new Episode("21", "14", "Postcards from the Wedge", "March 14, 2010"));
        episodes.add(new Episode("21", "15", "Stealing First Base", "March 21, 2010"));
        episodes.add(new Episode("21", "16", "The Greatest Story Ever D'ohed", "March 28, 2010"));
        episodes.add(new Episode("21", "17", "American History X-cellent", "April 11, 2010"));
        episodes.add(new Episode("21", "18", "Chief of Hearts", "April 18, 2010"));
        episodes.add(new Episode("21", "19", "The Squirt and the Whale", "April 25, 2010"));
        episodes.add(new Episode("21", "20", "To Surveil with Love", "May 2, 2010"));
        episodes.add(new Episode("21", "21", "Moe Letter Blues", "May 9, 2010"));
        episodes.add(new Episode("21", "22", "The Bob Next Door", "May 16, 2010"));
        episodes.add(new Episode("21", "23", "Judge Me Tender", "May 23, 2010"));
    
        episodes.add(new Episode("22", "1", "Elementary School Musical", "September 26, 2010"));
        episodes.add(new Episode("22", "2", "Loan-a Lisa", "October 3, 2010"));
        episodes.add(new Episode("22", "3", "MoneyBart", "October 10, 2010"));
        episodes.add(new Episode("22", "4", "Treehouse of Horror XXI", "November 7, 2010"));
        episodes.add(new Episode("22", "5", "Lisa Simpson, This Isn't Your Life", "November 14, 2010"));
        episodes.add(new Episode("22", "6", "The Fool Monty", "November 21, 2010"));
        episodes.add(new Episode("22", "7", "How Munched is That Birdie in the Window?", "November 28, 2010"));
        episodes.add(new Episode("22", "8", "The Fight Before Christmas", "December 5, 2010"));
        episodes.add(new Episode("22", "9", "Donnie Fatso", "December 12, 2010"));
        episodes.add(new Episode("22", "10", "Moms I'd Like to Forget", "January 9, 2011"));
        episodes.add(new Episode("22", "11", "Flaming Moe", "January 16, 2011"));
        episodes.add(new Episode("22", "12", "Homer the Father", "January 23, 2011"));
        episodes.add(new Episode("22", "13", "The Blue and the Gray", "February 13, 2011"));
        episodes.add(new Episode("22", "14", "Angry Dad: The Movie", "February 20, 2011"));
        episodes.add(new Episode("22", "15", "The Scorpion's Tale", "March 6, 2011"));
        episodes.add(new Episode("22", "16", "A Midsummer's Nice Dream", "March 13, 2011"));
        episodes.add(new Episode("22", "17", "Love Is a Many Strangled Thing", "March 27, 2011"));
        episodes.add(new Episode("22", "18", "The Great Simpsina", "April 10, 2011"));
        episodes.add(new Episode("22", "19", "The Real Housewives of Fat Tony", "May 1, 2011"));
        episodes.add(new Episode("22", "20", "Homer Scissorhands", "May 8, 2011"));
        episodes.add(new Episode("22", "21", "500 Keys", "May 15, 2011"));
        episodes.add(new Episode("22", "22", "The Ned-Liest Catch", "May 22, 2011"));
    
        episodes.add(new Episode("23", "1", "The Falcon and the D'ohman", "September 25, 2011"));
        episodes.add(new Episode("23", "2", "Bart Stops to Smell the Roosevelts", "October 2, 2011"));
        episodes.add(new Episode("23", "3", "Treehouse of Horror XXII", "October 30, 2011"));
        episodes.add(new Episode("23", "4", "Replaceable You", "November 6, 2011"));
        episodes.add(new Episode("23", "5", "The Food Wife", "November 13, 2011"));
        episodes.add(new Episode("23", "6", "The Book Job", "November 20, 2011"));
        episodes.add(new Episode("23", "7", "The Man in the Blue Flannel Pants", "November 27, 2011"));
        episodes.add(new Episode("23", "8", "The Ten-Per-Cent Solution", "December 4, 2011"));
        episodes.add(new Episode("23", "9", "Holidays of Future Passed", "December 11, 2011"));
        episodes.add(new Episode("23", "10", "Politically Inept, with Homer Simpson", "January 8, 2012"));
        episodes.add(new Episode("23", "11", "The D'oh-cial Network", "January 15, 2012"));
        episodes.add(new Episode("23", "12", "Moe Goes from Rags to Riches", "January 29, 2012"));
        episodes.add(new Episode("23", "13", "The Daughter Also Rises", "February 12, 2012"));
        episodes.add(new Episode("23", "14", "At Long Last Leave", "February 19, 2012"));
        episodes.add(new Episode("23", "15", "Exit Through the Kwik-E-Mart", "March 4, 2012"));
        episodes.add(new Episode("23", "16", "How I Wet Your Mother", "March 11, 2012"));
        episodes.add(new Episode("23", "17", "Them, Robot", "March 18, 2012"));
        episodes.add(new Episode("23", "18", "Beware My Cheating Bart", "April 15, 2012"));
        episodes.add(new Episode("23", "19", "A Totally Fun Thing That Bart Will Never Do Again", "April 29, 2012"));
        episodes.add(new Episode("23", "20", "The Spy Who Learned Me", "May 6, 2012"));
        episodes.add(new Episode("23", "21", "Ned 'n Edna's Blend", "May 13, 2012"));
        episodes.add(new Episode("23", "22", "Lisa Goes Gaga", "May 20, 2012"));
    
        episodes.add(new Episode("24", "1", "Moonshine River", "September 30, 2012"));
        episodes.add(new Episode("24", "2", "Treehouse of Horror XXIII", "October 7, 2012"));
        episodes.add(new Episode("24", "3", "Adventures in Baby-Getting", "November 4, 2012"));
        episodes.add(new Episode("24", "4", "Gone Abie Gone", "November 11, 2012"));
        episodes.add(new Episode("24", "5", "Penny-Wiseguys", "November 18, 2012"));
        episodes.add(new Episode("24", "6", "A Tree Grows in Springfield", "November 25, 2012"));
        episodes.add(new Episode("24", "7", "The Day the Earth Stood Cool", "December 9, 2012"));
        episodes.add(new Episode("24", "8", "To Cur with Love", "December 16, 2012"));
        episodes.add(new Episode("24", "9", "Homer Goes to Prep School", "January 6, 2013"));
        episodes.add(new Episode("24", "10", "A Test Before Trying", "January 13, 2013"));
        episodes.add(new Episode("24", "11", "The Changing of the Guardian", "January 27, 2013"));
        episodes.add(new Episode("24", "12", "Love Is a Many-Splintered Thing", "February 10, 2013"));
        episodes.add(new Episode("24", "13", "Hardly Kirk-ing", "February 17, 2013"));
        episodes.add(new Episode("24", "14", "Gorgeous Grampa", "March 3, 2013"));
        episodes.add(new Episode("24", "15", "Black Eyed, Please", "March 10, 2013"));
        episodes.add(new Episode("24", "16", "Dark Knight Court", "March 17, 2013"));
        episodes.add(new Episode("24", "17", "What Animated Women Want", "April 14, 2013"));
        episodes.add(new Episode("24", "18", "Pulpit Friction", "April 28, 2013"));
        episodes.add(new Episode("24", "19", "Whiskey Business", "May 5, 2013"));
        episodes.add(new Episode("24", "20", "The Fabulous Faker Boy", "May 12, 2013"));
        episodes.add(new Episode("24", "21", "The Saga of Carl", "May 19, 2013"));
        episodes.add(new Episode("24", "22", "Dangers on a Train", "May 19, 2013"));
    
        episodes.add(new Episode("25", "1", "Homerland", "September 29, 2013"));
        episodes.add(new Episode("25", "2", "Treehouse of Horror XXIV", "October 6, 2013"));
        episodes.add(new Episode("25", "3", "Four Regrettings and a Funeral", "November 3, 2013"));
        episodes.add(new Episode("25", "4", "YOLO", "November 10, 2013"));
        episodes.add(new Episode("25", "5", "Labor Pains", "November 17, 2013"));
        episodes.add(new Episode("25", "6", "The Kid Is All Right", "November 24, 2013"));
        episodes.add(new Episode("25", "7", "Yellow Subterfuge", "December 8, 2013"));
        episodes.add(new Episode("25", "8", "White Christmas Blues", "December 15, 2013"));
        episodes.add(new Episode("25", "9", "Steal This Episode", "January 5, 2014"));
        episodes.add(new Episode("25", "10", "Married to the Blob", "January 12, 2014"));
        episodes.add(new Episode("25", "11", "Specs and the City", "January 26, 2014"));
        episodes.add(new Episode("25", "12", "Diggs", "March 9, 2014"));
        episodes.add(new Episode("25", "13", "The Man Who Grew Too Much", "March 9, 2014"));
        episodes.add(new Episode("25", "14", "The Winter of His Content", "March 16, 2014"));
        episodes.add(new Episode("25", "15", "The War of Art", "March 23, 2014"));
        episodes.add(new Episode("25", "16", "You Don't Have to Live Like a Referee", "March 30, 2014"));
        episodes.add(new Episode("25", "17", "Luca$", "April 6, 2014"));
        episodes.add(new Episode("25", "18", "Days of Future Future", "April 13, 2014"));
        episodes.add(new Episode("25", "19", "What to Expect When Bart's Expecting", "April 27, 2014"));
        episodes.add(new Episode("25", "20", "Brick Like Me", "May 4, 2014"));
        episodes.add(new Episode("25", "21", "Pay Pal", "May 11, 2014"));
        episodes.add(new Episode("25", "22", "The Yellow Badge of Cowardge", "May 18, 2014"));
    
 /*       episodes.add(new Episode("26", "1", "Clown in the Dumps", "September 28, 2014"));
        episodes.add(new Episode("26", "2", "The Wreck of the Relationship", "October 5, 2014"));
        episodes.add(new Episode("26", "3", "Super Franchise Me", "October 12, 2014"));
        episodes.add(new Episode("26", "4", "Treehouse of Horror XXV", "October 19, 2014"));
        episodes.add(new Episode("26", "5", "Opposites A-Frack", "November 2, 2014"));
        episodes.add(new Episode("26", "6", "Simpsorama", "November 9, 2014"));
        episodes.add(new Episode("26", "7", "Blazed and Confused", "November 16, 2014"));
        episodes.add(new Episode("26", "8", "Covercraft", "November 23, 2014"));
        episodes.add(new Episode("26", "9", "I Won't Be Home for Christmas", "December 7, 2014"));
        episodes.add(new Episode("26", "10", "The Man Who Came to Be Dinner", "January 4, 2015"));
        episodes.add(new Episode("26", "11", "Bart's New Friend", "January 11, 2015"));
        episodes.add(new Episode("26", "12", "The Musk Who Fell to Earth", "January 25, 2015"));
        episodes.add(new Episode("26", "13", "Walking Big & Tall", "February 8, 2015"));
        episodes.add(new Episode("26", "14", "My Fare Lady", "February 15, 2015"));
        episodes.add(new Episode("26", "15", "The Princess Guide", "March 1, 2015"));
        episodes.add(new Episode("26", "16", "Sky Police", "March 8, 2015"));
        episodes.add(new Episode("26", "17", "Waiting for Duffman", "March 15, 2015"));
        episodes.add(new Episode("26", "18", "Peeping Mom", "April 19, 2015"));
        episodes.add(new Episode("26", "19", "The Kids Are All Fight", "April 26, 2015"));
        episodes.add(new Episode("26", "20", "Let's Go Fly a Coot", "May 3, 2015"));
        episodes.add(new Episode("26", "21", "Bull-E", "May 10, 2015"));
        episodes.add(new Episode("26", "22", "Mathlete's Feat", "May 17, 2015"));*/
    
        episodes.add(new Episode("27", "1", "Every Man's Dream", "September 27, 2015"));
        episodes.add(new Episode("27", "2", "Cue Detective", "October 4, 2015"));
        episodes.add(new Episode("27", "3", "Puffless", "October 11, 2015"));
        episodes.add(new Episode("27", "4", "Halloween of Horror", "October 18, 2015"));
        episodes.add(new Episode("27", "5", "Treehouse of Horror XXVI", "October 25, 2015"));
        episodes.add(new Episode("27", "6", "Friend with Benefit", "November 8, 2015"));
        episodes.add(new Episode("27", "7", "Lisa with an 'S'", "November 22, 2015"));
        episodes.add(new Episode("27", "8", "Paths of Glory", "December 6, 2015"));
        episodes.add(new Episode("27", "9", "Barthood", "December 13, 2015"));
        episodes.add(new Episode("27", "10", "The Girl Code", "January 3, 2016"));
        episodes.add(new Episode("27", "11", "Teenage Mutant Milk-Caused Hurdles", "January 10, 2016"));
        episodes.add(new Episode("27", "12", "Much Apu About Something", "January 17, 2016"));
        episodes.add(new Episode("27", "13", "Love Is in the N2-O2-Ar-CO2-Ne-He-CH4", "February 14, 2016"));
        episodes.add(new Episode("27", "14", "Gal of Constant Sorrow", "February 21, 2016"));
        episodes.add(new Episode("27", "15", "Lisa the Veterinarian", "March 6, 2016"));
        episodes.add(new Episode("27", "16", "The Marge-ian Chronicles", "March 13, 2016"));
        episodes.add(new Episode("27", "17", "The Burns Cage", "April 3, 2016"));
        episodes.add(new Episode("27", "18", "How Lisa Got Her Marge Back", "April 10, 2016"));
        episodes.add(new Episode("27", "19", "Fland Canyon", "April 24, 2016"));
        episodes.add(new Episode("27", "20", "To Courier with Love", "May 8, 2016"));
        episodes.add(new Episode("27", "21", "Simprovised", "May 15, 2016"));
        episodes.add(new Episode("27", "22", "Orange Is the New Yellow", "May 22, 2016"));
    
        episodes.add(new Episode("28", "1", "Monty Burns' Fleeing Circus", "September 25, 2016"));
        episodes.add(new Episode("28", "2", "Friends and Family", "October 2, 2016"));
        episodes.add(new Episode("28", "3", "The Town", "October 9, 2016"));
        episodes.add(new Episode("28", "4", "Treehouse of Horror XXVII", "October 16, 2016"));
        episodes.add(new Episode("28", "5", "Trust but Clarify", "October 23, 2016"));
        episodes.add(new Episode("28", "6", "There Will Be Buds", "November 6, 2016"));
        episodes.add(new Episode("28", "7", "Havana Wild Weekend", "November 13, 2016"));
        episodes.add(new Episode("28", "8", "Dad Behavior", "November 20, 2016"));
        episodes.add(new Episode("28", "9", "The Last Traction Hero", "December 4, 2016"));
        episodes.add(new Episode("28", "10", "The Nightmare After Krustmas", "December 11, 2016"));
        episodes.add(new Episode("28", "11", "Pork and Burns", "January 8, 2017"));
        episodes.add(new Episode("28", "12", "The Great Phatsby (Part One)", "January 15, 2017"));
        episodes.add(new Episode("28", "13", "The Great Phatsby (Part Two)", "January 15, 2017"));
        episodes.add(new Episode("28", "14", "Fatzcarraldo", "February 12, 2017"));
        episodes.add(new Episode("28", "15", "The Cad and the Hat", "February 19, 2017"));
        episodes.add(new Episode("28", "16", "Kamp Krustier", "March 5, 2017"));
        episodes.add(new Episode("28", "17", "22 for 30", "March 12, 2017"));
        episodes.add(new Episode("28", "18", "A Father's Watch", "March 19, 2017"));
        episodes.add(new Episode("28", "19", "Caper Chase", "April 2, 2017"));
        episodes.add(new Episode("28", "20", "Looking for Mr. Goodbart", "April 30, 2017"));
        episodes.add(new Episode("28", "21", "Moho House", "May 7, 2017"));
        episodes.add(new Episode("28", "22", "Dogtown", "May 21, 2017"));
    
        episodes.add(new Episode("29", "1", "The Serfsons", "October 1, 2017"));
        episodes.add(new Episode("29", "2", "Springfield Splendor", "October 8, 2017"));
        episodes.add(new Episode("29", "3", "Whistler's Father", "October 15, 2017"));
        episodes.add(new Episode("29", "4", "Treehouse of Horror XXVIII", "October 22, 2017"));
        episodes.add(new Episode("29", "5", "Grampy Can Ya Hear Me", "November 5, 2017"));
        episodes.add(new Episode("29", "6", "The Old Blue Mayor She Ain't What She Used to Be", "November 12, 2017"));
        episodes.add(new Episode("29", "7", "Singin' in the Lane", "November 19, 2017"));
        episodes.add(new Episode("29", "8", "Mr. Lisa's Opus", "December 3, 2017"));
        episodes.add(new Episode("29", "9", "Gone Boy", "December 10, 2017"));
        episodes.add(new Episode("29", "10", "Haw-Haw Land", "January 7, 2018"));
        episodes.add(new Episode("29", "11", "Frink Gets Testy", "January 14, 2018"));
        episodes.add(new Episode("29", "12", "Homer Is Where the Art Isn't", "March 18, 2018"));
        episodes.add(new Episode("29", "13", "3 Scenes Plus a Tag from a Marriage", "March 25, 2018"));
        episodes.add(new Episode("29", "14", "Fears of a Clown", "April 1, 2018"));
        episodes.add(new Episode("29", "15", "No Good Read Goes Unpunished", "April 8, 2018"));
        episodes.add(new Episode("29", "16", "King Leer", "April 15, 2018"));
        episodes.add(new Episode("29", "17", "Lisa Gets the Blues", "April 22, 2018"));
        episodes.add(new Episode("29", "18", "Forgive and Regret", "April 29, 2018"));
        episodes.add(new Episode("29", "19", "Left Behind", "May 6, 2018"));
        episodes.add(new Episode("29", "20", "Throw Grampa from the Dane", "May 13, 2018"));
        episodes.add(new Episode("29", "21", "Flanders' Ladder", "May 20, 2018"));
    /*
        episodes.add(new Episode("30", "1", "Bart's Not Dead", "September 30, 2018"));
        episodes.add(new Episode("30", "2", "Heartbreak Hotel", "October 7, 2018"));
        episodes.add(new Episode("30", "3", "My Way or the Highway to Heaven", "October 14, 2018"));
        episodes.add(new Episode("30", "4", "Treehouse of Horror XXIX", "October 21, 2018"));
        episodes.add(new Episode("30", "5", "Baby You Can't Drive My Car", "November 4, 2018"));
        episodes.add(new Episode("30", "6", "From Russia Without Love", "November 11, 2018"));
        episodes.add(new Episode("30", "7", "Werking Mom", "November 18, 2018"));
        episodes.add(new Episode("30", "8", "Krusty the Clown", "November 25, 2018"));
        episodes.add(new Episode("30", "9", "Daddicus Finch", "December 2, 2018"));
        episodes.add(new Episode("30", "10", "'Tis the 30th Season", "December 9, 2018"));
    
    /*Specials
    episodes.add(new Episode("0", "", "Homer and Bart visiting NFL on FOX", "September 3, 1995"));
    episodes.add(new Episode("0", "", "Springfield's Most Wanted", "September 17, 1995"));
    episodes.add(new Episode("0", "", "The Simpsons: America's First Family", "June 23, 2000"));
    episodes.add(new Episode("0", "", "My Wasted Life", "June 23, 2000"));
    episodes.add(new Episode("0", "", "The Simpsons' Quiz Show", "November 5, 2004"));
    episodes.add(new Episode("0", "", "Ultimate Guide to The Simpsons", "November 5, 2004"));
    episodes.add(new Episode("0", "", "The Simpsons' Christmas Message", "December 25, 2004"));
    episodes.add(new Episode("0", "", "Homer Introduces American Idol", "May 16, 2007"));
    episodes.add(new Episode("0", "", "Homer's Monolouge on The Tonight Show", "July 24, 2007"));
    episodes.add(new Episode("0", "", "The Simpsons: A Culture Show", "July 25, 2007"));
    episodes.add(new Episode("0", "", "The Simpsons Ride", "May 15, 2008"));
    episodes.add(new Episode("0", "", "Homer's Colonoscopy", "September 5, 2008"));
    episodes.add(new Episode("0", "", "Late Show Top Ten List", "2008"));
    episodes.add(new Episode("0", "", "Homer Congratulates Huell!", "December 1, 2009"));
    episodes.add(new Episode("0", "", "The Simpsons 20th Anniversary Special: In 3D! On Ice!", "January 10, 2010"));
    episodes.add(new Episode("0", "", "The Simpsons: Access All Areas", "January 11, 2010"));
    episodes.add(new Episode("0", "", "The Simpsons: Mischief & Mayhem", "January 12, 2010"));
    episodes.add(new Episode("0", "", "The Simpsons: Celebrity Friends", "January 13, 2010"));
    episodes.add(new Episode("0", "", "The Simpsons SU2C PSA", "September 10, 2010"));
    episodes.add(new Episode("0", "", "Late Show Top Ten List", "2010"));
    episodes.add(new Episode("0", "", "FOX's 25th Anniversary Special", "April 22, 2010"));
    episodes.add(new Episode("0", "", "The Longest Daycare", "July 13, 2012"));
    episodes.add(new Episode("0", "", "Homer Votes 2012", "September 20, 2012"));
    episodes.add(new Episode("0", "", "Debate Reaction", "October 5, 2012"));
    episodes.add(new Episode("0", "", "A Message From Springfield Republican Party Headquarters", "October 22, 2012"));
    episodes.add(new Episode("0", "", "Mr. Burns Endorses Romney", "November 1, 2012"));
    episodes.add(new Episode("0", "", "Late Show Top Ten List", "November 8, 2012"));
    episodes.add(new Episode("0", "", "Fiscal Cliff", "December 4, 2012"));
    episodes.add(new Episode("0", "", "Maggie Sucks", "January 18, 2013"));
    episodes.add(new Episode("0", "", "Oscor-Nominated", "January 31, 2013"));
    episodes.add(new Episode("0", "", "Homer Shake", "March 1, 2013"));
    episodes.add(new Episode("0", "", "A Day in the Life...with Yeardley Smith", "March 18-20, 2013"));
    episodes.add(new Episode("0", "", "Super Bowl Promo", "January 26, 2014"));
    episodes.add(new Episode("0", "", "Simpsons Ice Bucket Challenge", "August 26, 2014"));
    episodes.add(new Episode("0", "", "Willie's View On Scottish Independence", "September 12, 2014"));
    episodes.add(new Episode("0", "", "The Simpsons Take the Bowl", "September 12-13-14, 2014"));
    episodes.add(new Episode("0", "", "The Simpsons Guy", "September 28, 2014"));
    episodes.add(new Episode("0", "", "Pixel Touch Gag Submission", "February 13, 2015"));
    episodes.add(new Episode("0", "", "Trumptastic Voyage", "July 7, 2015"));
    episodes.add(new Episode("0", "", "Marge Simpson's ALS Ice Bucket Challenge", "September 8, 2015"));
    episodes.add(new Episode("0", "", "Join The Simpsons At The Daytona 500", "February 10, 2016"));
    episodes.add(new Episode("0", "", "The Debateful Eight", "Febriary 20, 2016"));
    episodes.add(new Episode("0", "", "Pokémon Now?", "July 16, 2016"));
    episodes.add(new Episode("0", "", "Homer From The Green Room At San Diego Comic-Con 2016", "July 23, 2016"));
    episodes.add(new Episode("0", "", "3 a.m.", "July 30, 2016"));
    episodes.add(new Episode("0", "", "Jimmy Kimmel Live!", "October 13, 2016"));
    episodes.add(new Episode("0", "", "Homer Votes 2016", "October 14, 2016"));
    episodes.add(new Episode("0", "", "Happy Daytona Day", "February 9, 2017"));
    episodes.add(new Episode("0", "", "Donald Trump's First 100 Days In Office", "April 26, 2017"));
    episodes.add(new Episode("0", "", "125 Days: Donald Trump Makes One Last Try To Patch Things Up With Comey", ""));
    episodes.add(new Episode("0", "", "Moe Live Tweets!", "July 3, 2017"));
    episodes.add(new Episode("0", "", "A Public Announcement About the Eclipse", "August 27, 2017"));
    episodes.add(new Episode("0", "", "Springfield of Dreams: The Legend of Homer Simpson", "October 22, 2017"));
    episodes.add(new Episode("0", "", "A Message from Moe About Puerto Rico", "November 3, 2017"));
    episodes.add(new Episode("0", "", "Mueller Meets Trump", "December 14, 2017"));
    episodes.add(new Episode("0", "", "A Tale of Two Trumps", "March 23, 2018"));
    */
    

		
		
		
		return episodes;
	}

}
